version: '3.8'

services:
  proxy:
    image: proyecto-cc/proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - app_nat
    restart: always
    
  backend:
    image: proyecto-cc/backend-v1
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app_nat
    restart: always

  frontend:
    image: proyecto-cc/frontend-v2
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app_nat
    environment:
      - VUE_APP_API_MACHINE=http://192.168.178.29:80
    restart: always

  database:
    image: postgres
    container_name: my-postgres-database
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: music_chops
    ports:
      - "5432:5432"
    networks:
      - app_nat
    restart: always

networks:
  app_nat:
    driver: bridge

