version: '3.8'

services:
  backend:
    image: proyecto-cc/backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app_nat
    restart: always

  frontend:
    image: proyecto-cc/frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app_nat
    restart: always

  database:
    image: postgres
    container_name: my-postgres-database
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: music_chops
    ports:
      - "5432:5432"
    networks:
      - app_nat
    restart: always

networks:
  app_nat:
    driver: bridge

