name: Integración continua v.0.1

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install ffmpeg
              run: sudo apt install -y ffmpeg

            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12.7'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Start API and run tests
              run: |
                flask --app api run --host='0.0.0.0' &
                sleep 2
                pytest test_basics.py
                kill -9 `lsof -i:5000 -t`